In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

from collections import Counter
import math

In [2]:
# 例 4.1 
lambda_ = 0.2
x = [2, 'S']

X1 = [1,2,3]
X2 = ['S', 'M', 'L']
Y = [1, -1]

In [4]:
class NB:
    def __init__(self, lambda_):
        self.lambda_ = lambda_
        
    def fit(self, X, y):
        N, M = X.shape
        data = np.hstack((X, y.reshape(N, 1)))
        
        py = {}
        pxy = {}
        uniquey, countsy = np.unique(y, return_counts=True)
        tmp = dict(zip(uniquey, countsy))
        for k,v in tmp.items():
            py[k] = (v + self.lambda_)/(N + len(uniquey) * self.lambda_)
            tmp_data = data[data[:, -1] == k]
            for col in range(M):
                uniquecol, countscol = np.unique(tmp_data[:,col], return_counts=True)
                tmp1 = dict(zip(uniquecol, countscol))
                for kk, vv in tmp1.items():
                    pxy['X({})={}|Y={}'.format(col+1, kk, k)] = (vv + self.lambda_)/(v + len(uniquecol) * self.lambda_)
                    
        self.py = py
        self.pxy = pxy

        #return self.py, self.pxy
    
    def predict(self, x):
        M = len(x)
        res = {}
        for k,v in self.py.items():
            p = v
            for i in range(len(x)):
                p = p * self.pxy['X({})={}|Y={}'.format(i+1, x[i], k)]
            res[k] = p
        print(res)
        maxp = -1
        maxk = -1
        for kk,vv in res.items():
            if vv > maxp:
                maxp = vv
                maxk = kk
                
        return maxk

In [5]:
lambda_ = 0.2
d = {'S':0, 'M':1, 'L':2}

X = np.array([[1, d['S']], [1, d['M']], [1, d['M']],
             [1, d['S']], [1, d['S']], [2, d['S']],
             [2, d['M']], [2, d['M']], [2, d['L']],
             [2, d['L']], [3, d['L']], [3, d['M']],
             [3, d['M']], [3, d['L']], [3, d['L']]])

y = np.array([-1, -1, 1, 1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, -1])

In [6]:
X

array([[1, 0],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 0],
       [2, 0],
       [2, 1],
       [2, 1],
       [2, 2],
       [2, 2],
       [3, 2],
       [3, 1],
       [3, 1],
       [3, 2],
       [3, 2]])

In [7]:
y

array([-1, -1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1, -1])

In [8]:
model = NB(lambda_)
model.fit(X,y)
model.predict(np.array([2, 0]))

{-1: 0.06506624688442873, 1: 0.024891774891774892}


-1

In [9]:
# data
def create_data():
    iris = load_iris()
    df = pd.DataFrame(iris.data, columns=iris.feature_names)
    df['label'] = iris.target
    df.columns = ['sepal length', 'sepal width', 'petal length', 'petal width', 'label']
    data = np.array(df.iloc[:100, :])
    # print(data)
    return data[:,:-1], data[:,-1]

In [10]:
X, y = create_data()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [11]:
X_test[0], y_test[0]

(array([5. , 3.2, 1.2, 0.2]), 0.0)

In [12]:
X_train.shape

(70, 4)

In [13]:
class NaiveBayes:
    def fit(self, X, y):
        self.classes = list(np.unique(y))
        self.parameters = {}
        
        for c in self.classes:
            # 计算每个种类的平均值，方差，先验概率
            X_Index_c = X[np.where(y == c)]
            X_index_c_mean = np.mean(X_Index_c, axis=0, keepdims=True)
            X_index_c_var = np.var(X_Index_c, axis=0, keepdims=True)
            parameters = {"mean": X_index_c_mean, "var": X_index_c_var, "prior": X_Index_c.shape[0] / X.shape[0]}
            self.parameters["class" + str(c)] = parameters
            print(self.parameters)
            
    def _pdf(self, X, classes):
        # 一维高斯分布的概率密度函数
        eps = 1e-4
        mean = self.parameters["class" + str(classes)]["mean"]
        var = self.parameters["class" + str(classes)]["var"]
        
        numerator = np.exp(-(X - mean) ** 2 / (2 * var + eps))
        denominator = np.sqrt(2 * np.pi * var + eps)
        
        # 取对数防止数值溢出
        result = np.sum(np.log(numerator / denominator), axis=1, keepdims=True)
        
        return result.T
    def _predict(self, X):
        output = []
        for y in self.classes:
            prior = np.log(self.parameters["class" + str(y)]["prior"])
            posterior = self._pdf(X, y)
            prediction = prior + posterior
            output.append(prediction)
        return output
    
    def predict(self, X):
        # 取概率最大的类别返回预测值
        output = self._predict(X)
        output = np.reshape(output, (len(self.classes), X.shape[0]))
        prediction = np.argmax(output, axis=0)
        return prediction
    
    def score(self, X_test, y_test):
        right = 0
        pred = self.predict(X_test)
        right = (y_test - pred == 0).sum()
        return right / float(len(X_test))

In [14]:
model = NaiveBayes()

In [15]:
model.fit(X_train, y_train)

{'class0.0': {'mean': array([[5.05666667, 3.45      , 1.48666667, 0.27      ]]), 'var': array([[0.15245556, 0.17383333, 0.02848889, 0.01343333]]), 'prior': 0.42857142857142855}}
{'class0.0': {'mean': array([[5.05666667, 3.45      , 1.48666667, 0.27      ]]), 'var': array([[0.15245556, 0.17383333, 0.02848889, 0.01343333]]), 'prior': 0.42857142857142855}, 'class1.0': {'mean': array([[5.9175, 2.7675, 4.26  , 1.31  ]]), 'var': array([[0.22544375, 0.08319375, 0.1774    , 0.0344    ]]), 'prior': 0.5714285714285714}}


In [16]:
print(model.predict(X_test))

[0 0 0 1 0 0 0 0 0 1 1 1 0 1 0 1 0 0 0 1 0 0 1 1 1 0 0 0 0 0]


In [17]:
model.score(X_test, y_test)

1.0

In [18]:
from sklearn.naive_bayes import GaussianNB

In [19]:
clf = GaussianNB()
clf.fit(X, y)

GaussianNB()

In [21]:
clf.predict([[2, 0]])

ValueError: operands could not be broadcast together with shapes (1,2) (4,) 

In [22]:
from sklearn.naive_bayes import BernoulliNB, MultinomialNB # 伯努利模型和多项式模型

In [26]:
clf1 = BernoulliNB()
clf1.fit(X, y)
clf1.predict([[2, 0]])

ValueError: Expected input with 4 features, got 2 instead

In [24]:
clf2 = MultinomialNB()
clf2.fit(X, y)
clf2.predict([[2, 0]])

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 2)